In [1]:
import numpy as np

# Pregunta 1

In [2]:
A = np.array([0,0])
puntos = [(4, 2), (2, -6), (-4, 3), (0, 5), (-4, 0), (-3, 5), (0, -3), (4, -3), (2, 5), (-7, -3)]

In [15]:
for i, punto in enumerate(puntos):
    AB = np.array(punto) - A
    print(f'Vector {i} - {AB}')
    
    x, y = AB
    
    print(f"Módulo: {round(np.linalg.norm(AB), 4)}")
    print(f"Sentido: {round(np.degrees(np.arctan2(y, x)), 4)}")
    print('-'*30)

Vector 0 - [4 2]
Módulo: 4.4721
Sentido: 26.5651
------------------------------
Vector 1 - [ 2 -6]
Módulo: 6.3246
Sentido: -71.5651
------------------------------
Vector 2 - [-4  3]
Módulo: 5.0
Sentido: 143.1301
------------------------------
Vector 3 - [0 5]
Módulo: 5.0
Sentido: 90.0
------------------------------
Vector 4 - [-4  0]
Módulo: 4.0
Sentido: 180.0
------------------------------
Vector 5 - [-3  5]
Módulo: 5.831
Sentido: 120.9638
------------------------------
Vector 6 - [ 0 -3]
Módulo: 3.0
Sentido: -90.0
------------------------------
Vector 7 - [ 4 -3]
Módulo: 5.0
Sentido: -36.8699
------------------------------
Vector 8 - [2 5]
Módulo: 5.3852
Sentido: 68.1986
------------------------------
Vector 9 - [-7 -3]
Módulo: 7.6158
Sentido: -156.8014
------------------------------


# Pregunta 2

In [16]:
vectores = (
    [(1,2), (2,5)], 
    [(-8,2), (-5,-6)], 
    [(2,-2), (1, -5)]
    )
for i, points_pair in enumerate(vectores):
    a, b = points_pair
    AB = np.array(b) - np.array(a)
    print(f'Vector {i}')
    x, y = AB
    
    print(f"Módulo: {round(np.linalg.norm(AB), 4)}")
    print(f"Sentido: {round(np.degrees(np.arctan2(y, x)), 4)}")
    print('-'*30)

Vector 0
Módulo: 3.1623
Sentido: 71.5651
------------------------------
Vector 1
Módulo: 8.544
Sentido: -69.444
------------------------------
Vector 2
Módulo: 3.1623
Sentido: -108.4349
------------------------------


# Pregunta 6

In [18]:
A = np.array([1,2,3])
B = np.array([0,-1,2])
C = np.array([-2,7,0])

# Método 1: Comprobar proporcionalidad entre sus coordenadas

AB = B - A
AC = C - A

print(AB[0] / AC[0])
print(AB[1] / AC[1])
print(AB[2] / AC[2])

0.3333333333333333
-0.6
0.3333333333333333


No hay proporcionalidad entre sus componentes, por lo que no estan alineados

In [19]:
# Método 2: Comprobar que el determinate es 0 y el rango es 2

M = np.array([AB, AC])
N = np.array([AB[:2], AC[:2]])

print(np.linalg.det(N) == 0)
print(np.linalg.matrix_rank(M) == 2)

False
True


Como se puede ver no estan alineados ya que el determinante es diferente de 0.

# Pregunta 7

In [20]:
A = np.array([2, 0, -4])
B = np.array([-4, 4, 2])
medio = (A + B) / 2
medio

array([-1.,  2., -1.])

# Pregunta 8

In [21]:
A = np.array([2, 0, -4])
B = np.array([-4, 4, 2])
AB = B - A

norma = np.linalg.norm(AB)
unitario = AB / norma

M = (norma / 3) * unitario

t1 = np.round(A + M, 4)
t2 = np.round(t1 + M, 4)

t1, t2

(array([-0.    ,  1.3333, -2.    ]), array([-2.    ,  2.6666,  0.    ]))

# Pregunta 10

In [22]:
u = np.array([1, 2, 1])
v = np.array([1, 2, 2])
w = np.array([0, 0, 3])
z = np.array([-2, 4, 3])

M = np.array([v, w, z]).T
MA = np.c_[M, u]
M_rank = np.linalg.matrix_rank(M)
MA_rank = np.linalg.matrix_rank(MA)

print(M_rank == MA_rank)
print(M_rank == 3)

print(np.linalg.det(M))

x = np.linalg.solve(M, u)
x

True
True
-23.999999999999993


array([ 1.        , -0.33333333, -0.        ])